#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01).
# Let’s also add other subdomains to make our life easier
# and write a Bash script that will display information about subdomains.
