#!/usr/bin/env bash
#instala nginx y cambia su pagina de inicio por holberton school

sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod 777 /var/www/html/index.html
echo 'Holberton School' > /var/www/html/index.html
sudo service nginx start
