#!/usr/bin/env bash
# bucles de 1 a 10 y muestra
# + "bad luck" para la cuarta iteración del ciclo
# + "good luck" para la octava iteración del ciclo
# + "Holberton School" para las otras iteraciones

COUNTER=1
while [ "$COUNTER" -le 10 ]; do
    if [ $COUNTER -eq 4 ]; then
	echo "bad luck"
    elif [ $COUNTER -eq 8 ]; then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    let COUNTER=COUNTER+1
done