#!/usr/bin/env bash
# muestra los números del 1 al 20 y muestra
# + "bad luck from China" después de la cuarta iteración del ciclo
# + "bad luck from Japón" después de la iteración del noveno ciclo
# + "bad luck from Italia" después de la iteración del ciclo 17

COUNTER=1
while [ "$COUNTER" -le 20 ]; do
    echo "$COUNTER"
    case "$COUNTER" in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    let COUNTER=COUNTER+1
done
