#!/usr/bin/env bash
# muestra el tiempo de 12 horas y 59 minutos

HOURS=0
while [ $HOURS -lt 13 ]
do
    echo "Hour: $HOURS"
    MINUTES=1
    while [ $MINUTES -lt 60 ]
    do
        echo $MINUTES
	    let MINUTES+=1
    done
    let HOURS+=1
done
